import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import Chart from "~/c/ControlledChart";
import JsonEditor from "~/c/JsonEditor";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <JsonEditor />
      <Chart />
    </div>
  );
};

export default Home;
